spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/storage
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
ui:
  location: file:///opt/oauth-identity-server/app/