apiVersion: v1
kind: ReplicationController
metadata:
  name: oauth-identity-server-rc
  labels:
    visualize: "true"
spec:
  replicas: 1
  selector:
    app: oauth-identity-server
  template:
    metadata:
      labels:
        app: oauth-identity-server
        visualize: "true"
    spec:
      containers:
      - name: proxy
        image: registry.accuratus-software.pl:5000/accuratus/oauth-identity-server:8
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ACC_ENV
          value: INT
        volumeMounts:
        - mountPath: "/var/log/accuratus"
          name: spreadium-logs
      volumes:
      - name: spreadium-logs
        glusterfs:
          endpoints: glusterfs-cluster
          path: spreadium-logs
          readOnly: false
      restartPolicy: Always
